version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'chalk'
  - package-ecosystem: 'npm'
    directory: '/packages/matrix'
    schedule:
      interval: 'yearly'
    ignore:
      - dependency-name: 'jest'
      - dependency-name: 'jest-*'
