version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/matrix'
    schedule:
      interval: 'never'
    ignore:
      - dependency-name: 'jest'
      - dependency-name: 'jest-*'
