title: jest-doctor Docs

markdown: kramdown

permalink: pretty

highlighter: rouge

version: 1.0.0

plugins:
  - jekyll-sitemap
  - jekyll-toc
  -
kramdown:
  auto_ids: true
  toc_levels: 2..2

compressor:
  css: true
  js: true
  html: true

url: 'https://stephan-dum.github.io'

baseurl: '/jest-doctor'

defaults:
  - scope:
      path: ''
    values:
      layout: default
