title: jest-doctor Docs

markdown: kramdown

permalink: pretty

highlighter: rouge

version: 1.0.0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

url: 'https://stephan-dum.github.io'

baseurl: '/jest-doctor'

excerpt_separator: '<!--more-->'

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
      excerpt_separator: '<!--more-->'
