title: jest-doctor Docs

markdown: kramdown

permalink: pretty

highlighter: rouge

version: 1.0.0

plugins:
  - jekyll-sitemap

url: 'https://stephan-dum.github.io'

baseurl: '/jest-doctor'

defaults:
  - scope:
      path: ''
    values:
      layout: default
